# Right hand position w.r.t right foot:
geometry_msgs/Point right_hand_position
# Direction of hand z-axis w.r.t right foot:
geometry_msgs/Vector3 right_hand_direction 

---
# Whole-body goal configuration generated:
float64[] wb_goal_config